/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	v1 "nexustempmodule/apis/gns.tsm.tanzu.vmware.com/v1"
	scheme "nexustempmodule/client/clientset/versioned/scheme"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DnsesGetter has a method to return a DnsInterface.
// A group's client should implement this interface.
type DnsesGetter interface {
	Dnses() DnsInterface
}

// DnsInterface has methods to work with Dns resources.
type DnsInterface interface {
	Create(ctx context.Context, dns *v1.Dns, opts metav1.CreateOptions) (*v1.Dns, error)
	Update(ctx context.Context, dns *v1.Dns, opts metav1.UpdateOptions) (*v1.Dns, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Dns, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DnsList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Dns, err error)
	DnsExpansion
}

// dnses implements DnsInterface
type dnses struct {
	client rest.Interface
}

// newDnses returns a Dnses
func newDnses(c *GnsTsmV1Client) *dnses {
	return &dnses{
		client: c.RESTClient(),
	}
}

// Get takes name of the dns, and returns the corresponding dns object, and an error if there is any.
func (c *dnses) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Dns, err error) {
	result = &v1.Dns{}
	err = c.client.Get().
		Resource("dnses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Dnses that match those selectors.
func (c *dnses) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DnsList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DnsList{}
	err = c.client.Get().
		Resource("dnses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dnses.
func (c *dnses) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("dnses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dns and creates it.  Returns the server's representation of the dns, and an error, if there is any.
func (c *dnses) Create(ctx context.Context, dns *v1.Dns, opts metav1.CreateOptions) (result *v1.Dns, err error) {
	result = &v1.Dns{}
	err = c.client.Post().
		Resource("dnses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dns).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dns and updates it. Returns the server's representation of the dns, and an error, if there is any.
func (c *dnses) Update(ctx context.Context, dns *v1.Dns, opts metav1.UpdateOptions) (result *v1.Dns, err error) {
	result = &v1.Dns{}
	err = c.client.Put().
		Resource("dnses").
		Name(dns.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dns).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dns and deletes it. Returns an error if one occurs.
func (c *dnses) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("dnses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dnses) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("dnses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dns.
func (c *dnses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Dns, err error) {
	result = &v1.Dns{}
	err = c.client.Patch(pt).
		Resource("dnses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
