---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: datamodels.nexus.vmware.com
spec:
  conversion:
    strategy: None
  group: nexus.vmware.com
  names:
    kind: Datamodel
    listKind: DatamodelList
    plural: datamodels
    shortNames:
    - datamodel
    singular: datamodel
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              name:
                type: string
              url:
                type: string
              title:
                type: string
                default: "Nexus API GW APIs"
              enableGraphql:
                type: boolean
                default: false
              graphqlPath:
                type: string
                default: ""
            type: object
    served: true
    storage: true
