apiVersion: v2
name: core
description: Nexus core components include ETCD,APIServer and Envoy.
type: application
version: 0.1.3
appVersion: "1.16.0"


dependencies:
  - name: allspark-common
    version: 0.2.4
    repository: "s3://allspark-helm-chart-repo/stable"
    alias: common
