---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    nexus: |
      {"name":"global.Org","children":{"projects.global.cosmos.tanzu.vmware.org":{"fieldName":"Project","fieldNameGvk":"projectGvk","isNamed":true}},"is_singleton":false,"nexus-rest-api-gen":{"uris":null}}
  creationTimestamp: null
  name: orgs.global.cosmos.tanzu.vmware.org
spec:
  conversion:
    strategy: None
  group: global.cosmos.tanzu.vmware.org
  names:
    kind: Org
    listKind: OrgList
    plural: orgs
    shortNames:
    - org
    singular: org
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              description:
                type: string
              license:
                type: string
              name:
                type: string
              projectGvk:
                additionalProperties:
                  properties:
                    group:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                  required:
                  - group
                  - kind
                  - name
                  type: object
                type: object
            type: object
          status:
            properties:
              nexus:
                properties:
                  remoteGeneration:
                    format: int64
                    type: integer
                  sourceGeneration:
                    format: int64
                    type: integer
                  syncerStatus:
                    properties:
                      cRGenerationId:
                        format: int64
                        type: integer
                      etcdVersion:
                        format: int64
                        type: integer
                    type: object
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1
