apiVersion: gns.vmware.org/v1
kind: GlobalNamespace
metadata:
  labels:
    projectId: default
  name : acme
spec:
  domain_name: acme.lab 
  name: acme
  use_shared_gateway: true
  ca: default
  ca_type: PreExistingCA
  match_conditions:
  - namespace:
      match: default
      type: EXACT
    cluster:
      match: aws-tmc-us-east
      type: EXACT
  api_discovery_enabled: true
