apiVersion: templates.vmware.org/v1
kind: HealthCheck
metadata:
  name : cli-demo
spec:
  name: cli-demo 
  protocol: HTTP
  domain: cli-demo.tanzu-sm.net
  port: 3000
  path: "/"
  healthThreshold: 3
  certificate_id: ''
  external_port: 80
  interval: 10
