--- 
assignees: 
  - xmen4xp
body: 
  - 
    attributes:
      value: "Thanks for taking the time to fill out this bug report!\n"
    type: markdown
  - 
    attributes: 
      description: "How can we get in touch with you if we need more info?"
      label: "Contact Details"
      placeholder: "ex. email@example.com"
    validations: 
      required: false
    id: contact
    type: input
  - 
    attributes: 
      description: "Tell us the project / group you are associated with"
      label: "Tell us the project / group you are associated with"
      options: 
        - "Community (Default)"
        - "Project ServiceMesh"
        - "Project Mazinger"
        - "Project Watch"
    validations: 
      required: true
    id: associated-project
    type: dropdown
  - 
    attributes: 
      description: "Describe the bug"
      label: "What happened?"
      placeholder: "Tell us what you see!"
      value: "A bug happened!"
    validations: 
      required: true
    id: what-happened
    type: textarea
  - 
    attributes: 
      description: "What was the expected behavior?"
      label: "Describe the expected behavior"
      placeholder: "What was the expected behavior?"
    validations: 
      required: false
    id: what-was-expected-behavior
    type: textarea
  - 
    attributes: 
      description: "Output of command - nexus version"
      label: "What version are you running?"
      placeholder: "Output of command - nexus version"
    validations: 
      required: false
    id: version
    type: textarea   
  - 
    attributes: 
      label: "How critical is this bug to you?"
      multiple: false
      options: 
        - "Blocker - solution is unusable without this feature"
        - "Critical - solution is severely limited in value without this feature"
        - "Major - important feature to be incorporated as there are no  known alternatives in the solution"
        - "Minor - nice to have feature that adds value to the solution"
    id: priority
    type: dropdown
    validations: 
      required: true
  - 
    attributes: 
      description: "Share with us, the steps to hit the bug"
      label: "How can we recreate the bug?"
      placeholder: "Share with us, the steps to hit the bug"
    validations: 
      required: false
    id: how-can-we-recreate-the-bug
    type: textarea
  - 
    type: markdown
    attributes:
      value: |
        **Can you share some basic diagnostic data?**
        
        Providing these would speed up resolution of the issue by many light years !
        For generic debug info, attach output of:
        ```
        nexus debug
        ```
        
        For compilation bugs, output of:
        ```
        nexus datamodel build --debug
        ```
        
        For installation bugs, output of:
        ```
        nexus prereq verify
        kubectl get pods -A -o yaml
        ```
  - 
    attributes: 
      description: "Any debug data that you are able to share?"
      label: "Any debug data that you are able to share?"
      placeholder: "Any debug data that you are able to share?"
    validations: 
      required: false
    id: debug
    type: textarea

  - 
    attributes: 
      label: "What is your operating system?"
      multiple: false
      options: 
        - Linux
        - MacOS
    id: "operating-system"
    type: dropdown
  - 
    attributes: 
      description: "Any additional / relevant info."
      label: "Any additional / relevant info"
    id: additional-info
    type: textarea
    validations: 
      required: false
description: "File a bug report"
labels: 
  - bug
name: "Bug Report"
title: "[Bug]: "
