// Code generated by nexus. DO NOT EDIT.

package v1

// +k8s:openapi-gen=true
type Child struct {
	Group string `json:"group" yaml:"group"`
	Kind  string `json:"kind" yaml:"kind"`
	Name  string `json:"name" yaml:"name"`
}

// +k8s:openapi-gen=true
type Link struct {
	Group string `json:"group" yaml:"group"`
	Kind  string `json:"kind" yaml:"kind"`
	Name  string `json:"name" yaml:"name"`
}

/* ------------------- CRDs definitions ------------------- */

// +k8s:openapi-gen=true
type ID struct {
	Id string `nexus.vmware:"id"`
}

// +k8s:openapi-gen=true
type Node struct {
	ID
}

// +k8s:openapi-gen=true
type RestUris struct {
	Uri     string   `json:"uri"`
	Methods []string `json:"methods"`
}

// +k8s:openapi-gen=true
type RestAPISpec struct {
	Uris []RestUris `json:"uris"`
}
