---
apiVersion: batch/v1
kind: Job
metadata:
  name: nexus-openapispec-installer
  namespace: '{{.Namespace}}'
  labels:
    app: nexus-openapispec-installer
    version: "{{.AS.ServiceVersion}}"
  annotations:
    "nexus-upgrade": "false"
spec:
  backoffLimit: 6
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      serviceAccountName: openapi-spec-creator-sa
      initContainers:
        - command:
            - "bin/bash"
            - "-c"
            - "cp /openapi.yaml /bin/apps"
          # yamllint disable-line rule:line-length
          image: "{{.AS.services.local.nexus-openapispec-installer.imageUrl}}"
          name: copy-spec
          volumeMounts:
            - name: shared-data
              mountPath: /bin/apps
      containers:
        - command:
            - "/bin/bash"
            - "-c"
            - |
              kubectl get configmap nexus-openapi -n {{.Namespace}} &&
              kubectl delete configmap nexus-openapi -n {{.Namespace}} ;
              kubectl create configmap nexus-openapi -n {{.Namespace}} --from-file=/bin/apps/openapi.yaml
          image: gcr.io/nsx-sm/tools:latest
          imagePullPolicy: IfNotPresent
          name: datamodel-installer-job
          volumeMounts:
            - name: shared-data
              mountPath: /bin/apps
      restartPolicy: Never
      volumes:
        - name: shared-data
          emptyDir: {}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openapi-spec-creator-role
  namespace: '{{.Namespace}}'
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - "*"
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: openapi-spec-creator-sa
  namespace: '{{.Namespace}}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openapi-spec-creator-rb
  namespace: '{{.Namespace}}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openapi-spec-creator-role
subjects:
  - kind: ServiceAccount
    name: openapi-spec-creator-sa
    namespace: '{{.Namespace}}'
