// Code generated by github.com/vmware-tanzu/graph-framework-for-microservices/gqlgen, DO NOT EDIT.

package model

type ConfigConfig struct {
	Id                *string                      `json:"Id"`
	ParentLabels      map[string]interface{}       `json:"ParentLabels"`
	ACPPolicies       []*PolicyAccessControlPolicy `json:"ACPPolicies"`
	FooExample        []*ConfigFooType             `json:"FooExample"`
	MyStr0            *string                      `json:"MyStr0"`
	MyStr1            *string                      `json:"MyStr1"`
	MyStr2            *string                      `json:"MyStr2"`
	XYZPort           *string                      `json:"XYZPort"`
	ABCHost           *string                      `json:"ABCHost"`
	ClusterNamespaces *string                      `json:"ClusterNamespaces"`
	TestValMarkers    *string                      `json:"TestValMarkers"`
	Instance          *float64                     `json:"Instance"`
	GNS               *GnsGns                      `json:"GNS"`
	DNS               *GnsDns                      `json:"DNS"`
	VMPPolicies       *PolicyVMpolicy              `json:"VMPPolicies"`
	Domain            *ConfigDomain                `json:"Domain"`
}

type ConfigDomain struct {
	Id               *string                `json:"Id"`
	ParentLabels     map[string]interface{} `json:"ParentLabels"`
	PointPort        *string                `json:"PointPort"`
	PointString      *string                `json:"PointString"`
	PointInt         *int                   `json:"PointInt"`
	PointMap         *string                `json:"PointMap"`
	PointSlice       *string                `json:"PointSlice"`
	SliceOfPoints    *string                `json:"SliceOfPoints"`
	SliceOfArrPoints *string                `json:"SliceOfArrPoints"`
	MapOfArrsPoints  *string                `json:"MapOfArrsPoints"`
	PointStruct      *string                `json:"PointStruct"`
}

type ConfigFooType struct {
	Id           *string                `json:"Id"`
	ParentLabels map[string]interface{} `json:"ParentLabels"`
	FooA         *string                `json:"FooA"`
	FooB         *string                `json:"FooB"`
	FooD         *string                `json:"FooD"`
	FooF         *string                `json:"FooF"`
}

type GnsBarChild struct {
	Id           *string                `json:"Id"`
	ParentLabels map[string]interface{} `json:"ParentLabels"`
	Name         *string                `json:"Name"`
}

type GnsDns struct {
	Id           *string                `json:"Id"`
	ParentLabels map[string]interface{} `json:"ParentLabels"`
}

type GnsGns struct {
	Id                       *string                    `json:"Id"`
	ParentLabels             map[string]interface{}     `json:"ParentLabels"`
	GnsServiceGroups         []*ServicegroupSvcGroup    `json:"GnsServiceGroups"`
	Dns                      *GnsDns                    `json:"Dns"`
	Domain                   *string                    `json:"Domain"`
	UseSharedGateway         *bool                      `json:"UseSharedGateway"`
	Description              *string                    `json:"Description"`
	Meta                     *string                    `json:"Meta"`
	Port                     *int                       `json:"Port"`
	OtherDescription         *string                    `json:"OtherDescription"`
	MapPointer               *string                    `json:"MapPointer"`
	SlicePointer             *string                    `json:"SlicePointer"`
	WorkloadSpec             *string                    `json:"WorkloadSpec"`
	DifferentSpec            *string                    `json:"DifferentSpec"`
	ServiceSegmentRef        *string                    `json:"ServiceSegmentRef"`
	ServiceSegmentRefPointer *string                    `json:"ServiceSegmentRefPointer"`
	ServiceSegmentRefs       *string                    `json:"ServiceSegmentRefs"`
	ServiceSegmentRefMap     *string                    `json:"ServiceSegmentRefMap"`
	GnsAccessControlPolicy   *PolicyAccessControlPolicy `json:"GnsAccessControlPolicy"`
	FooChild                 *GnsBarChild               `json:"FooChild"`
}

type GnsIgnoreChild struct {
	Id           *string                `json:"Id"`
	ParentLabels map[string]interface{} `json:"ParentLabels"`
	Name         *string                `json:"Name"`
}

type PolicyACPConfig struct {
	Id              *string                 `json:"Id"`
	ParentLabels    map[string]interface{}  `json:"ParentLabels"`
	DestSvcGroups   []*ServicegroupSvcGroup `json:"DestSvcGroups"`
	SourceSvcGroups []*ServicegroupSvcGroup `json:"SourceSvcGroups"`
	DisplayName     *string                 `json:"DisplayName"`
	Gns             *string                 `json:"Gns"`
	Description     *string                 `json:"Description"`
	Tags            *string                 `json:"Tags"`
	ProjectId       *string                 `json:"ProjectId"`
	Conditions      *string                 `json:"Conditions"`
}

type PolicyAccessControlPolicy struct {
	Id            *string                `json:"Id"`
	ParentLabels  map[string]interface{} `json:"ParentLabels"`
	PolicyConfigs []*PolicyACPConfig     `json:"PolicyConfigs"`
}

type PolicyVMpolicy struct {
	Id           *string                `json:"Id"`
	ParentLabels map[string]interface{} `json:"ParentLabels"`
}

type RootRoot struct {
	Id           *string                `json:"Id"`
	ParentLabels map[string]interface{} `json:"ParentLabels"`
	Config       *ConfigConfig          `json:"Config"`
}

type ServicegroupSvcGroup struct {
	Id           *string                `json:"Id"`
	ParentLabels map[string]interface{} `json:"ParentLabels"`
	DisplayName  *string                `json:"DisplayName"`
	Description  *string                `json:"Description"`
	Color        *string                `json:"Color"`
}
