apiVersion: admin.nexus.vmware.com/v1
kind: ProxyRule
metadata:
  name: header-based
  labels:
    nexuses.api.nexus.vmware.com: default
    configs.config.nexus.vmware.com: default
    apigateways.apigateway.nexus.vmware.com: default
spec:
  matchCondition:
    type: header
    key: x-tenant # the name of the HTTP header to use for routing
    value: "t-1"  # the value of the HTTP header
  upstream:
    scheme: http
    host: nexus-api-gw.default    # use the nexus-api-gw of tenant-1 as the destination
    port: 80
