// Code generated by nexus. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	"nexustempmodule/common"
)

// +k8s:openapi-gen=true
type Child struct {
	Group string `json:"group" yaml:"group"`
	Kind  string `json:"kind" yaml:"kind"`
	Name  string `json:"name" yaml:"name"`
}

// +k8s:openapi-gen=true
type Link struct {
	Group string `json:"group" yaml:"group"`
	Kind  string `json:"kind" yaml:"kind"`
	Name  string `json:"name" yaml:"name"`
}

// +k8s:openapi-gen=true
type NexusStatus struct {
	SourceGeneration int64 `json:"sourceGeneration" yaml:"sourceGeneration"`
	RemoteGeneration int64 `json:"remoteGeneration" yaml:"remoteGeneration"`
}

/* ------------------- CRDs definitions ------------------- */

// +genclient
// +genclient:noStatus
// +genclient:nonNamespaced
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +k8s:openapi-gen=true
type AdditionalPolicyData struct {
	metav1.TypeMeta   `json:",inline" yaml:",inline"`
	metav1.ObjectMeta `json:"metadata" yaml:"metadata"`
	Spec              AdditionalPolicyDataSpec        `json:"spec,omitempty" yaml:"spec,omitempty"`
	Status            AdditionalPolicyDataNexusStatus `json:"status,omitempty" yaml:"status,omitempty"`
}

// +k8s:openapi-gen=true
type AdditionalPolicyDataNexusStatus struct {
	Status AdditionalStatus `json:"status,omitempty" yaml:"status,omitempty"`
	Nexus  NexusStatus      `json:"nexus,omitempty" yaml:"nexus,omitempty"`
}

func (c *AdditionalPolicyData) CRDName() string {
	return "additionalpolicydatas.policypkg.tsm.tanzu.vmware.com"
}

func (c *AdditionalPolicyData) DisplayName() string {
	if c.GetLabels() != nil {
		return c.GetLabels()[common.DISPLAY_NAME_LABEL]
	}
	return ""
}

// +k8s:openapi-gen=true
type AdditionalPolicyDataSpec struct {
	Description AdditionalDescription `json:"description" yaml:"description"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type AdditionalPolicyDataList struct {
	metav1.TypeMeta `json:",inline" yaml:",inline"`
	metav1.ListMeta `json:"metadata" yaml:"metadata"`
	Items           []AdditionalPolicyData `json:"items" yaml:"items"`
}

// +genclient
// +genclient:noStatus
// +genclient:nonNamespaced
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +k8s:openapi-gen=true
type AccessControlPolicy struct {
	metav1.TypeMeta   `json:",inline" yaml:",inline"`
	metav1.ObjectMeta `json:"metadata" yaml:"metadata"`
	Spec              AccessControlPolicySpec        `json:"spec,omitempty" yaml:"spec,omitempty"`
	Status            AccessControlPolicyNexusStatus `json:"status,omitempty" yaml:"status,omitempty"`
}

// +k8s:openapi-gen=true
type AccessControlPolicyNexusStatus struct {
	Nexus NexusStatus `json:"nexus,omitempty" yaml:"nexus,omitempty"`
}

func (c *AccessControlPolicy) CRDName() string {
	return "accesscontrolpolicies.policypkg.tsm.tanzu.vmware.com"
}

func (c *AccessControlPolicy) DisplayName() string {
	if c.GetLabels() != nil {
		return c.GetLabels()[common.DISPLAY_NAME_LABEL]
	}
	return ""
}

// +k8s:openapi-gen=true
type AccessControlPolicySpec struct {
	PolicyConfigsGvk map[string]Child `json:"policy_configs_gvk,omitempty" yaml:"policy_configs_gvk,omitempty" nexus:"children"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type AccessControlPolicyList struct {
	metav1.TypeMeta `json:",inline" yaml:",inline"`
	metav1.ListMeta `json:"metadata" yaml:"metadata"`
	Items           []AccessControlPolicy `json:"items" yaml:"items"`
}

// +genclient
// +genclient:noStatus
// +genclient:nonNamespaced
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +k8s:openapi-gen=true
type ACPConfig struct {
	metav1.TypeMeta   `json:",inline" yaml:",inline"`
	metav1.ObjectMeta `json:"metadata" yaml:"metadata"`
	Spec              ACPConfigSpec        `json:"spec,omitempty" yaml:"spec,omitempty"`
	Status            ACPConfigNexusStatus `json:"status,omitempty" yaml:"status,omitempty"`
}

// +k8s:openapi-gen=true
type ACPConfigNexusStatus struct {
	Status ACPStatus   `json:"status,omitempty" yaml:"status,omitempty"`
	Nexus  NexusStatus `json:"nexus,omitempty" yaml:"nexus,omitempty"`
}

func (c *ACPConfig) CRDName() string {
	return "acpconfigs.policypkg.tsm.tanzu.vmware.com"
}

func (c *ACPConfig) DisplayName() string {
	if c.GetLabels() != nil {
		return c.GetLabels()[common.DISPLAY_NAME_LABEL]
	}
	return ""
}

// +k8s:openapi-gen=true
type ACPConfigSpec struct {
	DisplayName        string          `json:"display_name" yaml:"display_name"`
	Gns                string          `json:"gns" yaml:"gns"`
	Description        string          `json:"description" yaml:"description"`
	Tags               []string        `json:"tags" yaml:"tags"`
	ProjectId          string          `json:"project_id" yaml:"project_id"`
	Conditions         []string        `json:"conditions" yaml:"conditions"`
	DestSvcGroupsGvk   map[string]Link `json:"dest_svc_groups_gvk,omitempty" yaml:"dest_svc_groups_gvk,omitempty" nexus:"links"`
	SourceSvcGroupsGvk map[string]Link `json:"source_svc_groups_gvk,omitempty" yaml:"source_svc_groups_gvk,omitempty" nexus:"links"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type ACPConfigList struct {
	metav1.TypeMeta `json:",inline" yaml:",inline"`
	metav1.ListMeta `json:"metadata" yaml:"metadata"`
	Items           []ACPConfig `json:"items" yaml:"items"`
}

// +genclient
// +genclient:noStatus
// +genclient:nonNamespaced
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +k8s:openapi-gen=true
type VMpolicy struct {
	metav1.TypeMeta   `json:",inline" yaml:",inline"`
	metav1.ObjectMeta `json:"metadata" yaml:"metadata"`

	Status VMpolicyNexusStatus `json:"status,omitempty" yaml:"status,omitempty"`
}

// +k8s:openapi-gen=true
type VMpolicyNexusStatus struct {
	Nexus NexusStatus `json:"nexus,omitempty" yaml:"nexus,omitempty"`
}

func (c *VMpolicy) CRDName() string {
	return "vmpolicies.policypkg.tsm.tanzu.vmware.com"
}

func (c *VMpolicy) DisplayName() string {
	if c.GetLabels() != nil {
		return c.GetLabels()[common.DISPLAY_NAME_LABEL]
	}
	return ""
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type VMpolicyList struct {
	metav1.TypeMeta `json:",inline" yaml:",inline"`
	metav1.ListMeta `json:"metadata" yaml:"metadata"`
	Items           []VMpolicy `json:"items" yaml:"items"`
}

// +genclient
// +genclient:noStatus
// +genclient:nonNamespaced
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +k8s:openapi-gen=true
type RandomPolicyData struct {
	metav1.TypeMeta   `json:",inline" yaml:",inline"`
	metav1.ObjectMeta `json:"metadata" yaml:"metadata"`
	Spec              RandomPolicyDataSpec        `json:"spec,omitempty" yaml:"spec,omitempty"`
	Status            RandomPolicyDataNexusStatus `json:"status,omitempty" yaml:"status,omitempty"`
}

// +k8s:openapi-gen=true
type RandomPolicyDataNexusStatus struct {
	Status RandomStatus `json:"status,omitempty" yaml:"status,omitempty"`
	Nexus  NexusStatus  `json:"nexus,omitempty" yaml:"nexus,omitempty"`
}

func (c *RandomPolicyData) CRDName() string {
	return "randompolicydatas.policypkg.tsm.tanzu.vmware.com"
}

func (c *RandomPolicyData) DisplayName() string {
	if c.GetLabels() != nil {
		return c.GetLabels()[common.DISPLAY_NAME_LABEL]
	}
	return ""
}

// +k8s:openapi-gen=true
type RandomPolicyDataSpec struct {
	Description RandomDescription `json:"description" yaml:"description"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type RandomPolicyDataList struct {
	metav1.TypeMeta `json:",inline" yaml:",inline"`
	metav1.ListMeta `json:"metadata" yaml:"metadata"`
	Items           []RandomPolicyData `json:"items" yaml:"items"`
}

// +k8s:openapi-gen=true
type AdditionalDescription struct {
	DiscriptionA string `json:"discription_a" yaml:"discription_a"`
	DiscriptionB string `json:"discription_b" yaml:"discription_b"`
	DiscriptionC string `json:"discription_c" yaml:"discription_c"`
	DiscriptionD string `json:"discription_d" yaml:"discription_d"`
}

// +k8s:openapi-gen=true
type AdditionalStatus struct {
	StatusX int `json:"status_x" yaml:"status_x"`
	StatusY int `json:"status_y" yaml:"status_y"`
}

// +k8s:openapi-gen=true
type ACPStatus struct {
	StatusABC int `json:"status_abc" yaml:"status_abc"`
	StatusXYZ int `json:"status_xyz" yaml:"status_xyz"`
}

// +k8s:openapi-gen=true
type ResourceGroupRef struct {
	Name string `json:"name" yaml:"name"`
	Type string `json:"type" yaml:"type"`
}

// +k8s:openapi-gen=true
type ACPSvcGroupLinkInfo struct {
	ServiceName string `json:"service_name" yaml:"service_name"`
	ServiceType string `json:"service_type" yaml:"service_type"`
}

// +k8s:openapi-gen=true
type PolicyCfgAction struct {
	Action PolicyActionType `json:"action" mapstructure:"action" yaml:"action"`
}

// +k8s:openapi-gen=true
type ResourceGroupID struct {
	Name string `json:"name" mapstruction:"name" yaml:"name"`
	Type string `json:"type" mapstruction:"type" yaml:"type"`
}

// +k8s:openapi-gen=true
type RandomDescription struct {
	DiscriptionA string `json:"discription_a" yaml:"discription_a"`
	DiscriptionB string `json:"discription_b" yaml:"discription_b"`
	DiscriptionC string `json:"discription_c" yaml:"discription_c"`
	DiscriptionD string `json:"discription_d" yaml:"discription_d"`
}

// +k8s:openapi-gen=true
type RandomStatus struct {
	StatusX int `json:"status_x" yaml:"status_x"`
	StatusY int `json:"status_y" yaml:"status_y"`
}

type TempConst1 string
type TempConst2 string
type TempConst3 string
type PolicyActionType string
type PolicyCfgActions []PolicyCfgAction
type ResourceGroupIDs []ResourceGroupID
type RandomConst1 string
type RandomConst2 string
type RandomConst3 string

const (
	Const3                  TempConst3       = "Const3"
	Const2                  TempConst2       = "Const2"
	Const1                  TempConst1       = "Const1"
	PolicyActionType_Allow  PolicyActionType = "ALLOW"
	PolicyActionType_Deny   PolicyActionType = "DENY"
	PolicyActionType_Log    PolicyActionType = "LOG"
	PolicyActionType_Mirror PolicyActionType = "MIRROR"
	MyConst3                RandomConst3     = "Const3"
	MyConst2                RandomConst2     = "Const2"
	MyConst1                RandomConst1     = "Const1"
)
