/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	gnstsmtanzuvmwarecomv1 "gitlab.eng.vmware.com/nsx-allspark_users/nexus-sdk/compiler.git/example/output/crd_generated/apis/gns.tsm.tanzu.vmware.com/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEmptyDatas implements EmptyDataInterface
type FakeEmptyDatas struct {
	Fake *FakeGnsTsmV1
}

var emptydatasResource = schema.GroupVersionResource{Group: "gns.tsm.tanzu.vmware.com", Version: "v1", Resource: "emptydatas"}

var emptydatasKind = schema.GroupVersionKind{Group: "gns.tsm.tanzu.vmware.com", Version: "v1", Kind: "EmptyData"}

// Get takes name of the emptyData, and returns the corresponding emptyData object, and an error if there is any.
func (c *FakeEmptyDatas) Get(ctx context.Context, name string, options v1.GetOptions) (result *gnstsmtanzuvmwarecomv1.EmptyData, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(emptydatasResource, name), &gnstsmtanzuvmwarecomv1.EmptyData{})
	if obj == nil {
		return nil, err
	}
	return obj.(*gnstsmtanzuvmwarecomv1.EmptyData), err
}

// List takes label and field selectors, and returns the list of EmptyDatas that match those selectors.
func (c *FakeEmptyDatas) List(ctx context.Context, opts v1.ListOptions) (result *gnstsmtanzuvmwarecomv1.EmptyDataList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(emptydatasResource, emptydatasKind, opts), &gnstsmtanzuvmwarecomv1.EmptyDataList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &gnstsmtanzuvmwarecomv1.EmptyDataList{ListMeta: obj.(*gnstsmtanzuvmwarecomv1.EmptyDataList).ListMeta}
	for _, item := range obj.(*gnstsmtanzuvmwarecomv1.EmptyDataList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested emptyDatas.
func (c *FakeEmptyDatas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(emptydatasResource, opts))
}

// Create takes the representation of a emptyData and creates it.  Returns the server's representation of the emptyData, and an error, if there is any.
func (c *FakeEmptyDatas) Create(ctx context.Context, emptyData *gnstsmtanzuvmwarecomv1.EmptyData, opts v1.CreateOptions) (result *gnstsmtanzuvmwarecomv1.EmptyData, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(emptydatasResource, emptyData), &gnstsmtanzuvmwarecomv1.EmptyData{})
	if obj == nil {
		return nil, err
	}
	return obj.(*gnstsmtanzuvmwarecomv1.EmptyData), err
}

// Update takes the representation of a emptyData and updates it. Returns the server's representation of the emptyData, and an error, if there is any.
func (c *FakeEmptyDatas) Update(ctx context.Context, emptyData *gnstsmtanzuvmwarecomv1.EmptyData, opts v1.UpdateOptions) (result *gnstsmtanzuvmwarecomv1.EmptyData, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(emptydatasResource, emptyData), &gnstsmtanzuvmwarecomv1.EmptyData{})
	if obj == nil {
		return nil, err
	}
	return obj.(*gnstsmtanzuvmwarecomv1.EmptyData), err
}

// Delete takes name of the emptyData and deletes it. Returns an error if one occurs.
func (c *FakeEmptyDatas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(emptydatasResource, name), &gnstsmtanzuvmwarecomv1.EmptyData{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEmptyDatas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(emptydatasResource, listOpts)

	_, err := c.Fake.Invokes(action, &gnstsmtanzuvmwarecomv1.EmptyDataList{})
	return err
}

// Patch applies the patch and returns the patched emptyData.
func (c *FakeEmptyDatas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *gnstsmtanzuvmwarecomv1.EmptyData, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(emptydatasResource, name, pt, data, subresources...), &gnstsmtanzuvmwarecomv1.EmptyData{})
	if obj == nil {
		return nil, err
	}
	return obj.(*gnstsmtanzuvmwarecomv1.EmptyData), err
}
