/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	v1 "nexustempmodule/apis/policypkg.tsm.tanzu.vmware.com/v1"
	scheme "nexustempmodule/client/clientset/versioned/scheme"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ACPConfigsGetter has a method to return a ACPConfigInterface.
// A group's client should implement this interface.
type ACPConfigsGetter interface {
	ACPConfigs() ACPConfigInterface
}

// ACPConfigInterface has methods to work with ACPConfig resources.
type ACPConfigInterface interface {
	Create(ctx context.Context, aCPConfig *v1.ACPConfig, opts metav1.CreateOptions) (*v1.ACPConfig, error)
	Update(ctx context.Context, aCPConfig *v1.ACPConfig, opts metav1.UpdateOptions) (*v1.ACPConfig, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ACPConfig, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ACPConfigList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ACPConfig, err error)
	ACPConfigExpansion
}

// aCPConfigs implements ACPConfigInterface
type aCPConfigs struct {
	client rest.Interface
}

// newACPConfigs returns a ACPConfigs
func newACPConfigs(c *PolicypkgTsmV1Client) *aCPConfigs {
	return &aCPConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the aCPConfig, and returns the corresponding aCPConfig object, and an error if there is any.
func (c *aCPConfigs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ACPConfig, err error) {
	result = &v1.ACPConfig{}
	err = c.client.Get().
		Resource("acpconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ACPConfigs that match those selectors.
func (c *aCPConfigs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ACPConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ACPConfigList{}
	err = c.client.Get().
		Resource("acpconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aCPConfigs.
func (c *aCPConfigs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("acpconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a aCPConfig and creates it.  Returns the server's representation of the aCPConfig, and an error, if there is any.
func (c *aCPConfigs) Create(ctx context.Context, aCPConfig *v1.ACPConfig, opts metav1.CreateOptions) (result *v1.ACPConfig, err error) {
	result = &v1.ACPConfig{}
	err = c.client.Post().
		Resource("acpconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aCPConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a aCPConfig and updates it. Returns the server's representation of the aCPConfig, and an error, if there is any.
func (c *aCPConfigs) Update(ctx context.Context, aCPConfig *v1.ACPConfig, opts metav1.UpdateOptions) (result *v1.ACPConfig, err error) {
	result = &v1.ACPConfig{}
	err = c.client.Put().
		Resource("acpconfigs").
		Name(aCPConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aCPConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the aCPConfig and deletes it. Returns an error if one occurs.
func (c *aCPConfigs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("acpconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aCPConfigs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("acpconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched aCPConfig.
func (c *aCPConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ACPConfig, err error) {
	result = &v1.ACPConfig{}
	err = c.client.Patch(pt).
		Resource("acpconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
