// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_k8s_utils is a generated GoMock package.
package mock_k8s_utils

import (
	reflect "reflect"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// MockClientInt is a mock of ClientInt interface.
type MockClientInt struct {
	ctrl     *gomock.Controller
	recorder *MockClientIntMockRecorder
}

// MockClientIntMockRecorder is the mock recorder for MockClientInt.
type MockClientIntMockRecorder struct {
	mock *MockClientInt
}

// NewMockClientInt creates a new mock instance.
func NewMockClientInt(ctrl *gomock.Controller) *MockClientInt {
	mock := &MockClientInt{ctrl: ctrl}
	mock.recorder = &MockClientIntMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInt) EXPECT() *MockClientIntMockRecorder {
	return m.recorder
}

// ApplyCrd mocks base method.
func (m *MockClientInt) ApplyCrd(crd v1.CustomResourceDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyCrd", crd)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyCrd indicates an expected call of ApplyCrd.
func (mr *MockClientIntMockRecorder) ApplyCrd(crd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyCrd", reflect.TypeOf((*MockClientInt)(nil).ApplyCrd), crd)
}

// DeleteCrd mocks base method.
func (m *MockClientInt) DeleteCrd(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCrd", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCrd indicates an expected call of DeleteCrd.
func (mr *MockClientIntMockRecorder) DeleteCrd(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCrd", reflect.TypeOf((*MockClientInt)(nil).DeleteCrd), name)
}

// FetchCrds mocks base method.
func (m *MockClientInt) FetchCrds() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCrds")
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchCrds indicates an expected call of FetchCrds.
func (mr *MockClientIntMockRecorder) FetchCrds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCrds", reflect.TypeOf((*MockClientInt)(nil).FetchCrds))
}

// GetCrd mocks base method.
func (m *MockClientInt) GetCrd(name string) *v1.CustomResourceDefinition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCrd", name)
	ret0, _ := ret[0].(*v1.CustomResourceDefinition)
	return ret0
}

// GetCrd indicates an expected call of GetCrd.
func (mr *MockClientIntMockRecorder) GetCrd(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCrd", reflect.TypeOf((*MockClientInt)(nil).GetCrd), name)
}

// GetCrds mocks base method.
func (m *MockClientInt) GetCrds() []v1.CustomResourceDefinition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCrds")
	ret0, _ := ret[0].([]v1.CustomResourceDefinition)
	return ret0
}

// GetCrds indicates an expected call of GetCrds.
func (mr *MockClientIntMockRecorder) GetCrds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCrds", reflect.TypeOf((*MockClientInt)(nil).GetCrds))
}

// GetGroup mocks base method.
func (m *MockClientInt) GetGroup() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroup")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetGroup indicates an expected call of GetGroup.
func (mr *MockClientIntMockRecorder) GetGroup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroup", reflect.TypeOf((*MockClientInt)(nil).GetGroup))
}

// ListResources mocks base method.
func (m *MockClientInt) ListResources(crd v1.CustomResourceDefinition) ([]unstructured.Unstructured, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResources", crd)
	ret0, _ := ret[0].([]unstructured.Unstructured)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResources indicates an expected call of ListResources.
func (mr *MockClientIntMockRecorder) ListResources(crd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResources", reflect.TypeOf((*MockClientInt)(nil).ListResources), crd)
}

// ListResources mocks base method.
func (m *MockClientInt) FetchGroup(groupPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchGroup", groupPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListResources indicates an expected call of ListResources.
func (mr *MockClientIntMockRecorder) FetchGroup(crd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGroup", reflect.TypeOf((*MockClientInt)(nil).ListResources), crd)
}
