---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: foowrappers.test.it
spec:
  conversion:
    strategy: None
  group: test.it
  names:
    kind: Foowrapper
    listKind: FoowrapperList
    plural: foowrappers
    shortNames:
    - foowrapper
    singular: foowrapper
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          foo:
            properties:
              bar_value:
                properties:
                  enum_value:
                    type: string
                  oneof_value_int:
                    format: int32
                    type: integer
                  oneof_value_string:
                    type: string
                type: object
              bool_value:
                type: boolean
              bytes_value:
                format: byte
                type: string
              double_value:
                format: double
                type: number
              enum_value:
                type: string
              fixed32_value:
                format: int64
                type: integer
              fixed64_value:
                format: int64
                type: integer
              float_value:
                format: float
                type: number
              int32_value:
                format: int32
                type: integer
              int64_value:
                format: int64
                type: integer
              map_value:
                additionalProperties:
                  default: ""
                  type: string
                type: object
              nested_enum_value:
                type: string
              nested_message:
                properties:
                  nested_message_value:
                    type: string
                type: object
              oneof_value_int:
                format: int32
                type: integer
              oneof_value_string:
                type: string
              repeated_value:
                items:
                  default: 0
                  format: int32
                  type: integer
                type: array
              sfixed32_value:
                format: int32
                type: integer
              sfixed64_value:
                format: int64
                type: integer
              sint32_value:
                format: int32
                type: integer
              sint64_value:
                format: int64
                type: integer
              string_value:
                type: string
              uint32_value:
                format: int64
                type: integer
              uint64_value:
                format: int64
                type: integer
            type: object
          metadata:
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1
