---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    nexus: |
      {"name":"bar","is_singleton":false,"nexus-rest-api-gen":{"uris":null}}
  creationTimestamp: null
  name: bars.test.it
spec:
  conversion:
    strategy: None
  group: test.it
  names:
    kind: Bar
    listKind: BarList
    plural: bars
    shortNames:
    - bar
    singular: bar
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          foo:
            properties:
              buzz:
                type: integer
              fizz:
                type: string
            type: object
          metadata:
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1

