image:
  name: harbor-repo.vmware.com/nexus/runner:latest

include:
- project: "nsx-allspark_users/nexus-sdk/integration-tests"
  file: ".gitlab-ci-template.yml"

before_script:
  - git config --global url."https://gitlab.eng.vmware.com/".insteadOf "git@gitlab.eng.vmware.com:"
  - git config --global gc.auto 0
  - git config --global credential.helper store
  - echo -e  "https://gitlab-ci-token:${CICD_TOKEN}@gitlab.eng.vmware.com/" >> ~/.git-credentials

integration_test:
  stage: integration_test
  variables:
    DOCS_VERSION: $CI_COMMIT_SHA
  only:
    - merge_requests
    - master
  extends: .run_integration_test

stages:
  - integration_test
