exec:
  filename: generated/exec.go
model:
  filename: models/generated.go

autobind:
  - github.com/vmware-tanzu/graph-framework-for-microservices/src/gqlgen/_examples/starwars/models

models:
  ReviewInput:
    model: models.Review
  Starship:
    fields:
      length:
        resolver: true
