// Code generated by gitlab.eng.vmware.com/nsx-allspark_users/nexus-sdk/gqlgen.git, DO NOT EDIT.

package model

type TimeSeriesData struct {
	Code         *int    `json:"Code"`
	Message      *string `json:"Message"`
	Data         *string `json:"Data"`
	Last         *string `json:"Last"`
	TotalRecords *int    `json:"TotalRecords"`
}

type ConfigCluster struct {
	Name *string `json:"Name"`
	MyID *int    `json:"MyID"`
}

type ConfigConfig struct {
	Id                       *string         `json:"Id"`
	queryServiceTable        *TimeSeriesData `json:"queryServiceTable"`
	queryServiceVersionTable *TimeSeriesData `json:"queryServiceVersionTable"`
	queryServiceTS           *TimeSeriesData `json:"queryServiceTS"`
	queryIncomingAPIs        *TimeSeriesData `json:"queryIncomingAPIs"`
	queryOutgoingAPIs        *TimeSeriesData `json:"queryOutgoingAPIs"`
	queryIncomingTCP         *TimeSeriesData `json:"queryIncomingTCP"`
	queryOutgoingTCP         *TimeSeriesData `json:"queryOutgoingTCP"`
	queryServiceTopology     *TimeSeriesData `json:"queryServiceTopology"`
	GNS                      *GnsGns         `json:"GNS"`
	ConfigName               *string         `json:"ConfigName"`
	Cluster                  *ConfigCluster  `json:"Cluster"`
	FooA                     *string         `json:"FooA"`
	FooMap                   *string         `json:"FooMap"`
	FooB                     []*string       `json:"FooB"`
	FooD                     *string         `json:"FooD"`
	XYZPort                  []*int          `json:"XYZPort"`
	ABCHost                  []*string       `json:"ABCHost"`
}

type GnsBar struct {
	Id                       *string         `json:"Id"`
	queryServiceTable        *TimeSeriesData `json:"queryServiceTable"`
	queryServiceVersionTable *TimeSeriesData `json:"queryServiceVersionTable"`
	queryServiceTS           *TimeSeriesData `json:"queryServiceTS"`
	queryIncomingAPIs        *TimeSeriesData `json:"queryIncomingAPIs"`
	queryOutgoingAPIs        *TimeSeriesData `json:"queryOutgoingAPIs"`
	queryIncomingTCP         *TimeSeriesData `json:"queryIncomingTCP"`
	queryOutgoingTCP         *TimeSeriesData `json:"queryOutgoingTCP"`
	queryServiceTopology     *TimeSeriesData `json:"queryServiceTopology"`
	Name                     *string         `json:"Name"`
}

type GnsDescription struct {
	Color     *string  `json:"Color"`
	Version   *string  `json:"Version"`
	ProjectID *string  `json:"ProjectID"`
	Instance  *float64 `json:"Instance"`
}

type GnsEmptyData struct {
	Id                       *string         `json:"Id"`
	queryServiceTable        *TimeSeriesData `json:"queryServiceTable"`
	queryServiceVersionTable *TimeSeriesData `json:"queryServiceVersionTable"`
	queryServiceTS           *TimeSeriesData `json:"queryServiceTS"`
	queryIncomingAPIs        *TimeSeriesData `json:"queryIncomingAPIs"`
	queryOutgoingAPIs        *TimeSeriesData `json:"queryOutgoingAPIs"`
	queryIncomingTCP         *TimeSeriesData `json:"queryIncomingTCP"`
	queryOutgoingTCP         *TimeSeriesData `json:"queryOutgoingTCP"`
	queryServiceTopology     *TimeSeriesData `json:"queryServiceTopology"`
}

type GnsGns struct {
	Id                       *string           `json:"Id"`
	queryServiceTable        *TimeSeriesData   `json:"queryServiceTable"`
	queryServiceVersionTable *TimeSeriesData   `json:"queryServiceVersionTable"`
	queryServiceTS           *TimeSeriesData   `json:"queryServiceTS"`
	queryIncomingAPIs        *TimeSeriesData   `json:"queryIncomingAPIs"`
	queryOutgoingAPIs        *TimeSeriesData   `json:"queryOutgoingAPIs"`
	queryIncomingTCP         *TimeSeriesData   `json:"queryIncomingTCP"`
	queryOutgoingTCP         *TimeSeriesData   `json:"queryOutgoingTCP"`
	queryServiceTopology     *TimeSeriesData   `json:"queryServiceTopology"`
	FooLink                  *GnsBar           `json:"FooLink"`
	FooLinks                 []*GnsBar         `json:"FooLinks"`
	FooChild                 *GnsBar           `json:"FooChild"`
	FooChildren              []*GnsBar         `json:"FooChildren"`
	Domain                   *string           `json:"Domain"`
	UseSharedGateway         *bool             `json:"UseSharedGateway"`
	Mydesc                   *GnsDescription   `json:"Mydesc"`
	HostPort                 *GnsHostPort      `json:"HostPort"`
	TestArray                *GnsEmptyData     `json:"TestArray"`
	Instance                 *float64          `json:"Instance"`
	Array1                   []*int            `json:"Array1"`
	Array2                   []*GnsDescription `json:"Array2"`
	Array3                   []*GnsBar         `json:"Array3"`
	Array4                   []*float64        `json:"Array4"`
	Array5                   []*int            `json:"Array5"`
}

type GnsHostPort struct {
	Host *string `json:"Host"`
	Port *int    `json:"Port"`
}

type RootBar struct {
	Name *string `json:"Name"`
}

type RootRoot struct {
	Id                       *string         `json:"Id"`
	queryServiceTable        *TimeSeriesData `json:"queryServiceTable"`
	queryServiceVersionTable *TimeSeriesData `json:"queryServiceVersionTable"`
	queryServiceTS           *TimeSeriesData `json:"queryServiceTS"`
	queryIncomingAPIs        *TimeSeriesData `json:"queryIncomingAPIs"`
	queryOutgoingAPIs        *TimeSeriesData `json:"queryOutgoingAPIs"`
	queryIncomingTCP         *TimeSeriesData `json:"queryIncomingTCP"`
	queryOutgoingTCP         *TimeSeriesData `json:"queryOutgoingTCP"`
	queryServiceTopology     *TimeSeriesData `json:"queryServiceTopology"`
	Config                   *ConfigConfig   `json:"Config"`
	DisplayName              *string         `json:"DisplayName"`
	CustomBar                *RootBar        `json:"CustomBar"`
}
