// Code generated by gitlab.eng.vmware.com/nsx-allspark_users/nexus-sdk/gqlgen.git, DO NOT EDIT.

package model

type ConfigCluster struct {
	Name *string `json:"Name"`
	MyID *int    `json:"MyID"`
}

type ConfigConfig struct {
	Id         *string        `json:"Id"`
	GNS        *GnsGns        `json:"GNS"`
	ConfigName *string        `json:"ConfigName"`
	Cluster    *ConfigCluster `json:"Cluster"`
	FooA       *string        `json:"FooA"`
	FooMap     *string        `json:"FooMap"`
	FooB       []string       `json:"FooB"`
	FooD       *string        `json:"FooD"`
}

type GnsBar struct {
	Id   *string `json:"Id"`
	Name *string `json:"Name"`
}

type GnsDescription struct {
	Color     *string `json:"Color"`
	Version   *string `json:"Version"`
	ProjectID *string `json:"ProjectID"`
	Instance  *string `json:"Instance"`
}

type GnsGns struct {
	Id               *string         `json:"Id"`
	FooLink          *GnsBar         `json:"FooLink"`
	FooLinks         []*GnsBar       `json:"FooLinks"`
	FooChild         *GnsBar         `json:"FooChild"`
	FooChildren      []*GnsBar       `json:"FooChildren"`
	Domain           *string         `json:"Domain"`
	UseSharedGateway *bool           `json:"UseSharedGateway"`
	Mydesc           *GnsDescription `json:"Mydesc"`
	HostPort         *GnsHostPort    `json:"HostPort"`
	Instance         *string         `json:"Instance"`
}

type GnsHostPort struct {
	Host *string `json:"Host"`
	Port *int    `json:"Port"`
}

type RootBar struct {
	Name *string `json:"Name"`
}

type RootRoot struct {
	Id          *string       `json:"Id"`
	Config      *ConfigConfig `json:"Config"`
	DisplayName *string       `json:"DisplayName"`
	CustomBar   *RootBar      `json:"CustomBar"`
}
